const products = [
  {
    id: 1,
    name: "BENYAR",
    title: "watch",
    image: "https://m.media-amazon.com/images/I/814hrCDIz4L._SX679_.jpg",
    image1: "https://m.media-amazon.com/images/I/81rW8pqRZnL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/71y22YZ0XbL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/815OtGsB3rL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81RMQnHpMdL._SX679_.jpg",
    description:"BENYAR Automatic Mechanical Skeleton Leather Strap Men's Watch",
    price: "$299.99",
  },
  {
    id: 2,
    name: "Verido",
    title:"shoe",
    image: "https://m.media-amazon.com/images/I/616xMq9zXJL._SY741_.jpg",
    image1: "https://m.media-amazon.com/images/I/71PJEGrEPEL._SY741_.jpg",
    image2: "https://m.media-amazon.com/images/I/615M7gt6HyL._SY741_.jpg",
    image3: "https://m.media-amazon.com/images/I/717764CgyKL._SY741_.jpg",
    image4: "https://m.media-amazon.com/images/I/71JdCWe2EIL._SY741_.jpg",
    description:"Pure Cotton Men's Graphic Print Oversized Fit Half Sleeve Round Neck",
    price: "$199.99",
  },
  {
    id: 3,
    name: "Puma Neo Cat Mid 2.0",
    title:"shoe",
    image: "https://m.media-amazon.com/images/I/51qZ45UxF9L._SY695_.jpg",
    image1: "https://m.media-amazon.com/images/I/61oyoG8dzfL._SY695_.jpg",
    image2: "https://m.media-amazon.com/images/I/61xjkV5tnGL._SY695_.jpg",
    image3: "https://m.media-amazon.com/images/I/510mB4XBSVL._SY695_.jpg",
    image4: "https://m.media-amazon.com/images/I/51VXFlIJUAL._SY535_.jpg",
    description: "Unisex-Adult BMW MMS running sports shoes",
    price: "$399.99",
  },
  {
    id: 4,
    name: "Adidas Running Shoe",
    title:"shoe",
    image: "https://m.media-amazon.com/images/I/71NPlnbjxeL._SX695_.jpg",
    image1: "https://m.media-amazon.com/images/I/81LfipR3+yL._SX625_.jpg",
    image2: "https://m.media-amazon.com/images/I/71Xq-p+FsjL._SY625_.jpg",
    image3: "https://m.media-amazon.com/images/I/81tenaGhnnL._SX625_.jpg",
    image4: "https://m.media-amazon.com/images/I/81tenaGhnnL._SX625_.jpg",
    description: "Men Agora 1.0 Multisport Lightweight breathable shoes",
    price: "$129.99",
  },
  {
    id: 5,
    name: "Bee-Fits Oversized Tee",
    title:"tshirt",
    image: "https://m.media-amazon.com/images/I/51h7UxIK4uL.jpg",
    image1: "https://m.media-amazon.com/images/I/51Kqnev9X+L.jpg",
    image2: "https://m.media-amazon.com/images/I/81L+qg4Kb3L._SY741_.jpg",
    image3: "https://m.media-amazon.com/images/I/51h7UxIK4uL.jpg",
    image4: "https://m.media-amazon.com/images/I/61+gTTI3VUL.jpg",
    description: "Cotton dye wash oversized unisex printed T-shirt",
    price: "$9.99",
  },
  {
    id: 6,
    name: "Puma Slim Fit T-Shirt",
    title: "tshirt",
    image: "https://m.media-amazon.com/images/I/61VbsN6cjJL._SX679_.jpg",
    image1: "https://m.media-amazon.com/images/I/61UfBBBodZL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/71FowLdVC2L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/51CPPXjHSSL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/71ywoJVnxPL._SX679_.jpg",
    description: "Blue graphic slim-fit T-shirt",
    price: "$19.99",
  },
  {
    id: 7,
    name: "Boldfit Gym Bag",
    title:"bag",
    image: "https://m.media-amazon.com/images/I/71+aDeSfS5L._SX679_.jpg",
    image1: "https://m.media-amazon.com/images/I/615QDqnOvdL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/61AUfwpL3vL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/71L1WsLZQ0L._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/51d5fa2nwVL._SX679_.jpg",
    description: "Organized Duffle Bag with Adjustable Strap",
    price: "$15.99",
  },

  {
    id: 8,
    name: "THE BEAR HOUSE",
    title:"shirt",
    image: "https://m.media-amazon.com/images/I/61y07FX96RL._SY879_.jpg",
    image1: "https://m.media-amazon.com/images/I/81zeC6DBDML._SY741_.jpg",
    image2: "https://m.media-amazon.com/images/I/81Ef4BlcBmL._SY741_.jpg",
    image3: "https://m.media-amazon.com/images/I/71LLGPVysqL._SY741_.jpg",
    image4: "https://m.media-amazon.com/images/I/71eu-FpyyAL._SY741_.jpg",
    description: "Men's Checked Slim Fit Cotton Casual Shirt",
    price: "$29.99",
  },
  {
    id: 9,
    name: "Dennis Lingo Shirt",
    title:"shirt",
    image: "https://m.media-amazon.com/images/I/71NCBXev2YL._SY879_.jpg",
    image1: "https://m.media-amazon.com/images/I/91GPf3vyK1L._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/915C7GSuOOL._SX569_.jpg",
    image3: "https://m.media-amazon.com/images/I/813s-Y93KhL._SX569_.jpg",
    image4: "https://m.media-amazon.com/images/I/81aLtz3LFGL._SX569_.jpg",
    description: "Premium cotton slim-fit Men's Casual Shirt",
    price: "$24.99",
  },
  {
    id: 10,
    name: "Jockey Track Pants",
    title:"pant",
    image: "https://m.media-amazon.com/images/I/71vUWVMOSBL._SX466_.jpg",
    image1: "https://m.media-amazon.com/images/I/71A-iH9othL._SX466_.jpg",
    image2: "https://m.media-amazon.com/images/I/61ZzEPIwuHL._SX466_.jpg",
    image3: "https://m.media-amazon.com/images/I/61ifLdvoNbL._SX466_.jpg",
    image4: "https://m.media-amazon.com/images/I/61EVwf2zdHL._SX466_.jpg",
    description: "Soft cotton stretchable joggers",
    price: "$22.99",
  },
  {
    id: 11,
    name: "Hexagon Laptop Bag",
    title:"bag",
    image:"https://m.media-amazon.com/images/I/313wG+n2AbL._SY300_SX300_QL70_FMwebp_.jpg",
    image1: "https://m.media-amazon.com/images/I/81AMqxi4pUL._SL1500_.jpg",
    image2: "https://m.media-amazon.com/images/I/81fOOrKRf9L._SL1500_.jpg",
    image3: "https://m.media-amazon.com/images/I/81Udb0aEgjL._SL1500_.jpg",
    image4: "https://m.media-amazon.com/images/I/712P-YpFe8L._SL1500_.jpg",
    description: "Laptop Bag With Sleeve, Shoe Compartment & USB Charging",
    price: "$39.99",
  },
  {
    id: 12,
    name: "HRX Men Ankle Socks",
    title:"Socks",
    image: "https://m.media-amazon.com/images/I/812QkIIFUaL._SX679_.jpg",
    image1: "https://m.media-amazon.com/images/I/81EehgAUSoL._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/71xDtOD574L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81PmOI17bxL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/71vJtqt4fqL._SX679_.jpg",
    description: "Pack of 3 cotton rich ankle socks",
    price: "$6.99",
  },
  {
    id: 13,
    name: "Atowak Automatic",
    title: "watch",
    image: "https://m.media-amazon.com/images/I/71COV3ihJAL._SX679_.jpg",
    image1: "https://m.media-amazon.com/images/I/61D5fucPRdL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/71cIOvDNv4L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/71Rvk69ZlqL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81c5Ii-l6rL._SX679_.jpg",
    description: "Cobra Steel Silver Automatic Watch",
    price: "$49.99",
  },
  {
    id: 14,
    name: "Stuhrling Original",
    title: "watch",
    image: "https://m.media-amazon.com/images/I/818L0-9YYLL._SX679_.jpg",
    image1:"https://stuhrling.com/cdn/shop/products/3925.2-Legacy-MC1.jpg?v=1761320478&width=600",
    image2:"https://stuhrling.com/cdn/shop/products/3925.2-Legacy-MC4.jpg?v=1761320478&width=600",
    image3:"https://stuhrling.com/cdn/shop/products/3925.2-Legacy-LS3.jpg?v=1761320478&width=600",
    image4:"https://stuhrling.com/cdn/shop/products/3925.2-Legacy-MC2.jpg?v=1761320478&width=600",
    description: "Skeleton Automatic Watch for Men",
    price: "$1999.99",
  },
  {
    id: 15,
    name: "The Souled Store Store",
    title: "tshirt",
    image: "https://m.media-amazon.com/images/I/51cdyJYlVDL._SY695_.jpg",
    image1: "https://m.media-amazon.com/images/I/71pVJoK24EL._SY695_.jpg",
    image2: "https://m.media-amazon.com/images/I/712C0DdnpOL._SY695_.jpg",
    image3: "https://m.media-amazon.com/images/I/71ivarr8REL._SY695_.jpg",
    image4: "https://m.media-amazon.com/images/I/71IZqntoBXL._SY695_.jpg",
    description: "Naruto Sasuke High Top Sneakers",
    price: "$34.99",
  },
  {
    id: 16,
    name: "U.S. POLO ASSN",
    title: "shoe",
    image: "https://m.media-amazon.com/images/I/71TCP-Tq2VL._SY695_.jpg",
    image1: "https://m.media-amazon.com/images/I/71uzbhaf75L._SY625_.jpg",
    image2: "https://m.media-amazon.com/images/I/61L+EpbB+6L._SY625_.jpg",
    image3: "https://m.media-amazon.com/images/I/71t2KRfkVvL._SY625_.jpg",
    image4: "https://m.media-amazon.com/images/I/61ICZjzUlIL._SY625_.jpg",
    description: "Stylish Casual Sneaker Shoes",
    price: "$44.99",
  },
];
export default products;